events {}

http {


    upstream auth_service {

        server auth-service:4001;

    }


    server {


        listen 80;



        location /api/auth {


            proxy_pass http://auth_service;


            proxy_set_header Host $host;


            proxy_set_header X-Real-IP $remote_addr;


        }


        location / {


            return 200 "E-Commerce API Gateway Running";

        }

    }

}